name: bagel
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=11.0
  - cudnn
  - pip
  - pip:
    - scikit-learn
    - pandas
    - matplotlib
    - tensorflow
    - tensorflow-probability
